/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_conjure = 1,
  anon_sym_EQ = 2,
  anon_sym_enchant = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_incant = 7,
  anon_sym_curse = 8,
  anon_sym_evoke = 9,
  anon_sym_cast = 10,
  anon_sym_if = 11,
  anon_sym_else = 12,
  anon_sym_loop = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_EQ_EQ = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_LT = 18,
  anon_sym_LT_EQ = 19,
  anon_sym_GT = 20,
  anon_sym_GT_EQ = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_POUND = 26,
  aux_sym_comment_token1 = 27,
  anon_sym_POUND_POUND = 28,
  anon_sym_LF = 29,
  anon_sym_DQUOTE = 30,
  anon_sym_SQUOTE = 31,
  aux_sym__string_content_token1 = 32,
  anon_sym_DOLLAR = 33,
  anon_sym_DOLLAR_LBRACE = 34,
  sym_escape_sequence = 35,
  sym_number = 36,
  anon_sym_true = 37,
  anon_sym_false = 38,
  sym_identifier = 39,
  sym_source_file = 40,
  sym__definition = 41,
  sym_variable_declaration = 42,
  sym_function_declaration = 43,
  sym_parameter_list = 44,
  sym_output = 45,
  sym_error = 46,
  sym_command = 47,
  sym_function_call = 48,
  sym_argument_list = 49,
  sym_if_statement = 50,
  sym_loop_statement = 51,
  sym_block = 52,
  sym__expression = 53,
  sym_parenthesized_expression = 54,
  sym_binary_expression = 55,
  sym_comment = 56,
  sym_multiline_comment = 57,
  sym_string = 58,
  sym__string_content = 59,
  sym_string_interpolation = 60,
  sym_boolean = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_parameter_list_repeat1 = 63,
  aux_sym_argument_list_repeat1 = 64,
  aux_sym_multiline_comment_repeat1 = 65,
  aux_sym_string_repeat1 = 66,
  aux_sym_string_repeat2 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_conjure] = "conjure",
  [anon_sym_EQ] = "=",
  [anon_sym_enchant] = "enchant",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_incant] = "incant",
  [anon_sym_curse] = "curse",
  [anon_sym_evoke] = "evoke",
  [anon_sym_cast] = "cast",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_loop] = "loop",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_LF] = "\n",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__string_content_token1] = "_string_content_token1",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_variable_declaration] = "variable_declaration",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_output] = "output",
  [sym_error] = "error",
  [sym_command] = "command",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_if_statement] = "if_statement",
  [sym_loop_statement] = "loop_statement",
  [sym_block] = "block",
  [sym__expression] = "_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_comment] = "comment",
  [sym_multiline_comment] = "multiline_comment",
  [sym_string] = "string",
  [sym__string_content] = "_string_content",
  [sym_string_interpolation] = "string_interpolation",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_multiline_comment_repeat1] = "multiline_comment_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_conjure] = anon_sym_conjure,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_enchant] = anon_sym_enchant,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_incant] = anon_sym_incant,
  [anon_sym_curse] = anon_sym_curse,
  [anon_sym_evoke] = anon_sym_evoke,
  [anon_sym_cast] = anon_sym_cast,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__string_content_token1] = aux_sym__string_content_token1,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_output] = sym_output,
  [sym_error] = sym_error,
  [sym_command] = sym_command,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_if_statement] = sym_if_statement,
  [sym_loop_statement] = sym_loop_statement,
  [sym_block] = sym_block,
  [sym__expression] = sym__expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comment] = sym_comment,
  [sym_multiline_comment] = sym_multiline_comment,
  [sym_string] = sym_string,
  [sym__string_content] = sym__string_content,
  [sym_string_interpolation] = sym_string_interpolation,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_multiline_comment_repeat1] = aux_sym_multiline_comment_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_conjure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enchant] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_incant] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_curse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_evoke] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cast] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_body = 2,
  field_command = 3,
  field_condition = 4,
  field_consequence = 5,
  field_left = 6,
  field_message = 7,
  field_name = 8,
  field_operator = 9,
  field_right = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_body] = "body",
  [field_command] = "command",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_left] = "left",
  [field_message] = "message",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 3},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_message, 1},
  [1] =
    {field_command, 1},
  [2] =
    {field_body, 1},
  [3] =
    {field_condition, 1},
    {field_consequence, 2},
  [5] =
    {field_name, 1},
    {field_value, 3},
  [7] =
    {field_name, 1},
  [8] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [11] =
    {field_body, 4},
    {field_name, 1},
  [13] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [16] =
    {field_body, 5},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(49);
      ADVANCE_MAP(
        '!', 5,
        '"', 82,
        '#', 77,
        '$', 86,
        '\'', 83,
        '(', 54,
        ')', 55,
        '*', 75,
        '+', 73,
        ',', 56,
        '-', 74,
        '/', 76,
        '<', 69,
        '=', 52,
        '>', 71,
        '\\', 45,
        'c', 7,
        'e', 23,
        'f', 8,
        'i', 19,
        'l', 31,
        't', 33,
        '{', 65,
        '}', 66,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(81);
      if (lookahead == '#') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(82);
      if (lookahead == '$') ADVANCE(86);
      if (lookahead == '\'') ADVANCE(85);
      if (lookahead == '\\') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0) ADVANCE(85);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 82,
        '\'', 83,
        '(', 54,
        ')', 55,
        '=', 51,
        'c', 95,
        'f', 96,
        't', 100,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(82);
      if (lookahead == '\'') ADVANCE(83);
      if (lookahead == ')') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(68);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(67);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(26);
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(62);
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 'j') ADVANCE(44);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(37);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 'v') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 'v') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 45:
      ADVANCE_MAP(
        '"', 88,
        '$', 88,
        '\'', 88,
        '0', 88,
        '\\', 88,
        'n', 88,
        'r', 88,
        't', 88,
        '{', 88,
        '}', 88,
      );
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 47:
      if (eof) ADVANCE(49);
      ADVANCE_MAP(
        '!', 5,
        '"', 82,
        '#', 77,
        '$', 86,
        '\'', 83,
        '(', 54,
        ')', 55,
        '*', 75,
        '+', 73,
        ',', 56,
        '-', 74,
        '/', 76,
        '<', 69,
        '=', 52,
        '>', 71,
        'c', 7,
        'e', 23,
        'f', 8,
        'i', 19,
        'l', 31,
        't', 33,
        '{', 65,
        '}', 66,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 48:
      if (eof) ADVANCE(49);
      ADVANCE_MAP(
        '!', 5,
        '#', 77,
        ')', 55,
        '*', 75,
        '+', 73,
        ',', 56,
        '-', 74,
        '/', 76,
        '<', 69,
        '=', 6,
        '>', 71,
        'c', 7,
        'e', 25,
        'i', 19,
        'l', 31,
        '{', 65,
        '}', 66,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_conjure);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_enchant);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_incant);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_curse);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_evoke);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_cast);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_cast);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '\'') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 48},
  [3] = {.lex_state = 48},
  [4] = {.lex_state = 48},
  [5] = {.lex_state = 48},
  [6] = {.lex_state = 48},
  [7] = {.lex_state = 48},
  [8] = {.lex_state = 48},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 48},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 48},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 48},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 48},
  [36] = {.lex_state = 48},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 78},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 78},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_conjure] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_enchant] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_incant] = ACTIONS(1),
    [anon_sym_curse] = ACTIONS(1),
    [anon_sym_evoke] = ACTIONS(1),
    [anon_sym_cast] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(77),
    [sym__definition] = STATE(11),
    [sym_variable_declaration] = STATE(11),
    [sym_function_declaration] = STATE(11),
    [sym_output] = STATE(11),
    [sym_error] = STATE(11),
    [sym_command] = STATE(11),
    [sym_function_call] = STATE(11),
    [sym_if_statement] = STATE(11),
    [sym_loop_statement] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_multiline_comment] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_conjure] = ACTIONS(5),
    [anon_sym_enchant] = ACTIONS(7),
    [anon_sym_incant] = ACTIONS(9),
    [anon_sym_curse] = ACTIONS(11),
    [anon_sym_evoke] = ACTIONS(13),
    [anon_sym_cast] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_loop] = ACTIONS(19),
    [anon_sym_POUND] = ACTIONS(21),
    [anon_sym_POUND_POUND] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(27), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(25), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [30] = 2,
    ACTIONS(31), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(29), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [60] = 2,
    ACTIONS(35), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(33), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [90] = 2,
    ACTIONS(39), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(37), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [120] = 2,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(41), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [150] = 2,
    ACTIONS(47), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(45), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [180] = 2,
    ACTIONS(51), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_POUND,
    ACTIONS(49), 22,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND_POUND,
  [210] = 12,
    ACTIONS(55), 1,
      anon_sym_conjure,
    ACTIONS(58), 1,
      anon_sym_enchant,
    ACTIONS(61), 1,
      anon_sym_incant,
    ACTIONS(64), 1,
      anon_sym_curse,
    ACTIONS(67), 1,
      anon_sym_evoke,
    ACTIONS(70), 1,
      anon_sym_cast,
    ACTIONS(73), 1,
      anon_sym_if,
    ACTIONS(76), 1,
      anon_sym_loop,
    ACTIONS(79), 1,
      anon_sym_POUND,
    ACTIONS(82), 1,
      anon_sym_POUND_POUND,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(9), 12,
      sym__definition,
      sym_variable_declaration,
      sym_function_declaration,
      sym_output,
      sym_error,
      sym_command,
      sym_function_call,
      sym_if_statement,
      sym_loop_statement,
      sym_comment,
      sym_multiline_comment,
      aux_sym_source_file_repeat1,
  [259] = 12,
    ACTIONS(5), 1,
      anon_sym_conjure,
    ACTIONS(7), 1,
      anon_sym_enchant,
    ACTIONS(9), 1,
      anon_sym_incant,
    ACTIONS(11), 1,
      anon_sym_curse,
    ACTIONS(13), 1,
      anon_sym_evoke,
    ACTIONS(15), 1,
      anon_sym_cast,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_loop,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      anon_sym_POUND_POUND,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(12), 12,
      sym__definition,
      sym_variable_declaration,
      sym_function_declaration,
      sym_output,
      sym_error,
      sym_command,
      sym_function_call,
      sym_if_statement,
      sym_loop_statement,
      sym_comment,
      sym_multiline_comment,
      aux_sym_source_file_repeat1,
  [307] = 12,
    ACTIONS(5), 1,
      anon_sym_conjure,
    ACTIONS(7), 1,
      anon_sym_enchant,
    ACTIONS(9), 1,
      anon_sym_incant,
    ACTIONS(11), 1,
      anon_sym_curse,
    ACTIONS(13), 1,
      anon_sym_evoke,
    ACTIONS(15), 1,
      anon_sym_cast,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_loop,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      anon_sym_POUND_POUND,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(9), 12,
      sym__definition,
      sym_variable_declaration,
      sym_function_declaration,
      sym_output,
      sym_error,
      sym_command,
      sym_function_call,
      sym_if_statement,
      sym_loop_statement,
      sym_comment,
      sym_multiline_comment,
      aux_sym_source_file_repeat1,
  [355] = 12,
    ACTIONS(5), 1,
      anon_sym_conjure,
    ACTIONS(7), 1,
      anon_sym_enchant,
    ACTIONS(9), 1,
      anon_sym_incant,
    ACTIONS(11), 1,
      anon_sym_curse,
    ACTIONS(13), 1,
      anon_sym_evoke,
    ACTIONS(15), 1,
      anon_sym_cast,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_loop,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      anon_sym_POUND_POUND,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(9), 12,
      sym__definition,
      sym_variable_declaration,
      sym_function_declaration,
      sym_output,
      sym_error,
      sym_command,
      sym_function_call,
      sym_if_statement,
      sym_loop_statement,
      sym_comment,
      sym_multiline_comment,
      aux_sym_source_file_repeat1,
  [403] = 4,
    ACTIONS(97), 1,
      anon_sym_POUND,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(91), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [434] = 10,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    ACTIONS(103), 1,
      anon_sym_cast,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(109), 1,
      sym_number,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(74), 1,
      sym_argument_list,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 6,
      sym_function_call,
      sym__expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_string,
      sym_boolean,
  [471] = 8,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_cast,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(115), 1,
      sym_number,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 6,
      sym_function_call,
      sym__expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_string,
      sym_boolean,
  [502] = 8,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_cast,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(119), 1,
      sym_number,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 6,
      sym_function_call,
      sym__expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_string,
      sym_boolean,
  [533] = 8,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_cast,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(123), 1,
      sym_number,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 6,
      sym_function_call,
      sym__expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_string,
      sym_boolean,
  [564] = 8,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_cast,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 6,
      sym_function_call,
      sym__expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_string,
      sym_boolean,
  [595] = 8,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_cast,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(131), 1,
      sym_number,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 6,
      sym_function_call,
      sym__expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_string,
      sym_boolean,
  [626] = 2,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(135), 12,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_else,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [644] = 3,
    ACTIONS(141), 1,
      anon_sym_else,
    ACTIONS(143), 1,
      anon_sym_POUND,
    ACTIONS(139), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [664] = 5,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [688] = 2,
    ACTIONS(151), 1,
      anon_sym_POUND,
    ACTIONS(149), 12,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_else,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [706] = 2,
    ACTIONS(155), 1,
      anon_sym_POUND,
    ACTIONS(153), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [723] = 2,
    ACTIONS(159), 1,
      anon_sym_POUND,
    ACTIONS(157), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [740] = 2,
    ACTIONS(163), 1,
      anon_sym_POUND,
    ACTIONS(161), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [757] = 2,
    ACTIONS(167), 1,
      anon_sym_POUND,
    ACTIONS(165), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [774] = 2,
    ACTIONS(171), 1,
      anon_sym_POUND,
    ACTIONS(169), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [791] = 2,
    ACTIONS(175), 1,
      anon_sym_POUND,
    ACTIONS(173), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [808] = 4,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [829] = 2,
    ACTIONS(181), 1,
      anon_sym_POUND,
    ACTIONS(179), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [846] = 2,
    ACTIONS(185), 1,
      anon_sym_POUND,
    ACTIONS(183), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [863] = 2,
    ACTIONS(189), 1,
      anon_sym_POUND,
    ACTIONS(187), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [880] = 2,
    ACTIONS(193), 1,
      anon_sym_POUND,
    ACTIONS(191), 11,
      ts_builtin_sym_end,
      anon_sym_conjure,
      anon_sym_enchant,
      anon_sym_incant,
      anon_sym_curse,
      anon_sym_evoke,
      anon_sym_cast,
      anon_sym_if,
      anon_sym_loop,
      anon_sym_RBRACE,
      anon_sym_POUND_POUND,
  [897] = 3,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(93), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [916] = 3,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [934] = 5,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(203), 1,
      anon_sym_DOLLAR,
    ACTIONS(205), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(201), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    STATE(38), 3,
      sym__string_content,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [953] = 5,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    ACTIONS(212), 1,
      anon_sym_DOLLAR,
    ACTIONS(215), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(209), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    STATE(38), 3,
      sym__string_content,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [972] = 5,
    ACTIONS(203), 1,
      anon_sym_DOLLAR,
    ACTIONS(205), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(218), 1,
      anon_sym_DQUOTE,
    ACTIONS(220), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    STATE(37), 3,
      sym__string_content,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [991] = 2,
    ACTIONS(224), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    ACTIONS(222), 3,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
  [1001] = 3,
    ACTIONS(218), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    STATE(44), 2,
      sym__string_content,
      aux_sym_string_repeat2,
  [1013] = 3,
    ACTIONS(228), 1,
      anon_sym_SQUOTE,
    ACTIONS(230), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    STATE(42), 2,
      sym__string_content,
      aux_sym_string_repeat2,
  [1025] = 2,
    ACTIONS(235), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    ACTIONS(233), 3,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
  [1035] = 3,
    ACTIONS(199), 1,
      anon_sym_SQUOTE,
    ACTIONS(237), 2,
      aux_sym__string_content_token1,
      sym_escape_sequence,
    STATE(42), 2,
      sym__string_content,
      aux_sym_string_repeat2,
  [1047] = 4,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(29), 1,
      sym_string,
  [1060] = 4,
    ACTIONS(241), 1,
      anon_sym_POUND,
    ACTIONS(244), 1,
      anon_sym_POUND_POUND,
    ACTIONS(246), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_multiline_comment_repeat1,
  [1073] = 4,
    ACTIONS(249), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      anon_sym_POUND_POUND,
    ACTIONS(253), 1,
      anon_sym_LF,
    STATE(48), 1,
      aux_sym_multiline_comment_repeat1,
  [1086] = 4,
    ACTIONS(249), 1,
      anon_sym_POUND,
    ACTIONS(255), 1,
      anon_sym_POUND_POUND,
    ACTIONS(257), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_multiline_comment_repeat1,
  [1099] = 3,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_if_statement,
      sym_block,
  [1110] = 3,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    STATE(24), 1,
      sym_string,
  [1120] = 3,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_parameter_list_repeat1,
  [1130] = 3,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      sym_string,
  [1140] = 2,
    ACTIONS(263), 1,
      anon_sym_LF,
    ACTIONS(244), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
  [1148] = 3,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_argument_list_repeat1,
  [1158] = 3,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      sym_identifier,
    STATE(65), 1,
      sym_parameter_list,
  [1168] = 3,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_parameter_list_repeat1,
  [1178] = 3,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_parameter_list_repeat1,
  [1188] = 3,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_argument_list_repeat1,
  [1198] = 1,
    ACTIONS(273), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1203] = 2,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_block,
  [1210] = 2,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_block,
  [1217] = 2,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_block,
  [1224] = 1,
    ACTIONS(281), 1,
      aux_sym_comment_token1,
  [1228] = 1,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
  [1232] = 1,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
  [1236] = 1,
    ACTIONS(287), 1,
      anon_sym_EQ,
  [1240] = 1,
    ACTIONS(289), 1,
      sym_identifier,
  [1244] = 1,
    ACTIONS(291), 1,
      sym_identifier,
  [1248] = 1,
    ACTIONS(293), 1,
      sym_identifier,
  [1252] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1256] = 1,
    ACTIONS(297), 1,
      aux_sym_comment_token1,
  [1260] = 1,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
  [1264] = 1,
    ACTIONS(301), 1,
      sym_identifier,
  [1268] = 1,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
  [1272] = 1,
    ACTIONS(305), 1,
      sym_identifier,
  [1276] = 1,
    ACTIONS(307), 1,
      sym_identifier,
  [1280] = 1,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 150,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 259,
  [SMALL_STATE(11)] = 307,
  [SMALL_STATE(12)] = 355,
  [SMALL_STATE(13)] = 403,
  [SMALL_STATE(14)] = 434,
  [SMALL_STATE(15)] = 471,
  [SMALL_STATE(16)] = 502,
  [SMALL_STATE(17)] = 533,
  [SMALL_STATE(18)] = 564,
  [SMALL_STATE(19)] = 595,
  [SMALL_STATE(20)] = 626,
  [SMALL_STATE(21)] = 644,
  [SMALL_STATE(22)] = 664,
  [SMALL_STATE(23)] = 688,
  [SMALL_STATE(24)] = 706,
  [SMALL_STATE(25)] = 723,
  [SMALL_STATE(26)] = 740,
  [SMALL_STATE(27)] = 757,
  [SMALL_STATE(28)] = 774,
  [SMALL_STATE(29)] = 791,
  [SMALL_STATE(30)] = 808,
  [SMALL_STATE(31)] = 829,
  [SMALL_STATE(32)] = 846,
  [SMALL_STATE(33)] = 863,
  [SMALL_STATE(34)] = 880,
  [SMALL_STATE(35)] = 897,
  [SMALL_STATE(36)] = 916,
  [SMALL_STATE(37)] = 934,
  [SMALL_STATE(38)] = 953,
  [SMALL_STATE(39)] = 972,
  [SMALL_STATE(40)] = 991,
  [SMALL_STATE(41)] = 1001,
  [SMALL_STATE(42)] = 1013,
  [SMALL_STATE(43)] = 1025,
  [SMALL_STATE(44)] = 1035,
  [SMALL_STATE(45)] = 1047,
  [SMALL_STATE(46)] = 1060,
  [SMALL_STATE(47)] = 1073,
  [SMALL_STATE(48)] = 1086,
  [SMALL_STATE(49)] = 1099,
  [SMALL_STATE(50)] = 1110,
  [SMALL_STATE(51)] = 1120,
  [SMALL_STATE(52)] = 1130,
  [SMALL_STATE(53)] = 1140,
  [SMALL_STATE(54)] = 1148,
  [SMALL_STATE(55)] = 1158,
  [SMALL_STATE(56)] = 1168,
  [SMALL_STATE(57)] = 1178,
  [SMALL_STATE(58)] = 1188,
  [SMALL_STATE(59)] = 1198,
  [SMALL_STATE(60)] = 1203,
  [SMALL_STATE(61)] = 1210,
  [SMALL_STATE(62)] = 1217,
  [SMALL_STATE(63)] = 1224,
  [SMALL_STATE(64)] = 1228,
  [SMALL_STATE(65)] = 1232,
  [SMALL_STATE(66)] = 1236,
  [SMALL_STATE(67)] = 1240,
  [SMALL_STATE(68)] = 1244,
  [SMALL_STATE(69)] = 1248,
  [SMALL_STATE(70)] = 1252,
  [SMALL_STATE(71)] = 1256,
  [SMALL_STATE(72)] = 1260,
  [SMALL_STATE(73)] = 1264,
  [SMALL_STATE(74)] = 1268,
  [SMALL_STATE(75)] = 1272,
  [SMALL_STATE(76)] = 1276,
  [SMALL_STATE(77)] = 1280,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 7),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 7),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 6),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 6),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 5),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error, 2, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_error, 2, 0, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_statement, 2, 0, 3),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_statement, 2, 0, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_comment, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_comment, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_comment, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_comment, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5, 0, 8),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 5, 0, 8),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 2, 0, 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output, 2, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 9),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 9),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, 0, 10),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 6, 0, 10),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_interpolation, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_interpolation, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(42),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_interpolation, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_interpolation, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [241] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multiline_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multiline_comment_repeat1, 2, 0, 0),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_comment_repeat1, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mage(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mage",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}

#ifdef __cplusplus
}
#endif
