name: 🐛 Bug Report
description: Report a bug in the mage language
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - AndrewBazen

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Mage Version
      description: What version of mage are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running mage on?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Other Linux
        - Other
    validations:
      required: true

  - type: input
    id: architecture
    attributes:
      label: Architecture
      description: What architecture are you using?
      placeholder: e.g., x86_64, aarch64, arm64
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `mage script.mage`
        2. Execute command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happens?
    validations:
      required: true

  - type: textarea
    id: script
    attributes:
      label: Mage Script (if applicable)
      description: If this bug involves a specific mage script, please provide it here.
      render: bash
      placeholder: |
        #!/usr/bin/env mage

        incant "Example script that causes the bug"
        # ... rest of your script

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output or error messages.
      render: shell
      placeholder: |
        Error: ...
        Stack trace: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Package managers available: winget, choco
        - Environment variables: ...
        - Related issues: ...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
